---

- name: Check zabbix is installed
  yum:
    name: zabbix-agent.x86_64
    state: present
  when: ansible_local.foreman_status != 'Current'

- name: Copy zabbix-agent template
  template:
    src: templates/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: Restart zabbix-agent

- name: Add Firewall rules for Zabbix
  firewalld:
    port: 10050/tcp
    permanent: true
    state: enabled
