---

- name: Add Ansible user
  user:
      name: ansible
      group: wheel
      system: yes
      update_password: always
      password: "{{ user_password }}"
      comment: "Ansible Management User"

- name: Ensure Custom fact directory exists
  file:
      path: /etc/ansible/facts.d/
      state: directory

- name: Add custom fact file
  copy:
      src: files/foreman_status.fact
      dest: /etc/ansible/facts.d/foreman_status.fact
      mode: 0755

- name: Check SSH key is in authorized_keys
  authorized_key:
      user: ansible
      state: present
      key: "{{ ssh_key }}"

- name: Add SSH key to root user
  authorized_key:
      user: root
      state: present
      key: "{{ ssh_key }}"

- name: Install Foreman RPM
  yum:
      name: http://{{ foreman_host }}/pub/katello-ca-consumer-latest.noarch.rpm
      state: present

  tags:
       - satellite


- name: Register with Foreman
  redhat_subscription:
      state: present
      org_id: "{{ foreman_org }}"
      activationkey: "{{ foreman_act_key }}"
      pool_ids:
              - 2c9e80ee622e562c01622ea46a2b0061
              - 2c9e80ee622e562c01622e8f5d3a0006
              - 2c9e80ee622e562c01622e98fedd0046
  when:
        -  ansible_local.foreman_status != 'Current'
  ignore_errors: yes 


  tags:
       - satellite

- name: Install Packages
  yum:
      name: "{{ item }}"
      state: present
  with_items:
          #- katello-agent
      - vim
      - bash-completion
      - bind-utils
      - ipa-client

- name: Install Zabbix Repo Locally when Satellite not used
  yum:
      name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
      state: present   
  when: ansible_local.foreman_status != 'Current'  


- name: Update all packages
  yum:
     name: *
     state: latest

- name: Install Zabbix-agent
  yum:
      name: zabbix-agent
      state: present
      disable_gpg_check: yes
  notify: Start Zabbix-agent

- name: Install oVirt Guest Agent when no Satellite available
  yum:
      name: http://resources.ovirt.org/pub/yum-repo/ovirt-release42.rpm
      state: present
  when: ansible_local.foreman_status != 'Current'
  tags: ovirt

- name: Install oVirt Guest Agent
  yum: name=ovirt-guest-agent state=present
  notify: Start ovirt-guest-agent
  tags:
       - ovirt
                      
