---
- hosts: all 
  tasks:
          - name: Set Authorized Keys
            authorized_key:
              user: root
              state: present
              key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

