---

- hosts: all
  become: True
  become_method: sudo

  tasks:
    - name: Check net-snmp is installed
      yum:
        name: net-snmp
        state: present

    - name: Add user to /etc/snmp/snmpd.conf
      lineinfile:
        state: present
        path: /etc/snmp/snmpd.conf
        line: rouser svc_snmp1

    - name: Add user to /var/lib/net-snmp/snmpd.conf
      lineinfile:
        state: present
        path: /etc/snmp/snmpd.conf
        line: createUser svc_snmp1 MD5 "d2vvxUbXtCk83G8Y" DES "d2vvxUbXtCk83G8Y"

    - name: Ensure snmpd is restarted and enabled on boot
      service:
        name: snmpd
        state: restarted
        enabled: yes

