---

- hosts: localhost
  become: yes
  become_method: sudo

  tasks:
          - name: Add Ansible user account
            user:
              name: ansible
              system: yes
              password: 'Ru5slex?'
