- hosts: status_up
  tasks:
  - block:
        - name: RHEL System upgrade
          yum: 
              update_cache: yes
              name: '*'
              state: latest
              disable_gpg_check: true
          async: 3600
          poll: 10
          when:
              ansible_os_family == 'RedHat'

        - name: Fedora Update
          dnf:
              name: '*'
              state: latest
          async: 3600
          poll: 10
          when:
              ansible_distribution == 'Fedora'
    become: true
    become_method: sudo
    

  - block:
        - name: Check available updates
          win_updates:
                  state: searched
          register: update_count
        
        - name: List available updates
          debug: var=update_count
          
        - name: Windows Update
          win_updates:
            state: installed
          register: update_result
          tags: rollout

        - name: Reboot if required
          win_reboot:
             reboot_timeout: 3600
             test_command: whoami
          when: 
                update_result.reboot_required
    when:
        ansible_os_family == 'Windows'    


