- hosts: Windows
  become: yes
  tasks:
  - name: RHEL System upgrade
    yum: 
       update_cache=yes
       name=*
       state=latest
    when:
       ansible_distribution == 'CentOS'
       or
       ansible_distribution == 'RedHat'

  - name: Fedora Update
    dnf:
       name=*
       state=latest
    when:
       ansible_distribution == 'Fedora'

  - name: Windows Update
    win_updates:
            state: installed
    when:
        ansible_distribution == 'Microsoft Windows 10 Home'    

