---


- name: Check Zabbix repo is enabled
  redhat_subscription:
    state: present
    username: admin
    password: "{{ foreman_password }}"
    pool_ids:
        - ff80808160c690520160c6c77e860066
  tags:
        - satellite

- name: Check zabbix is installed
  yum:
    name: zabbix-agent.x86_64
    state: present

- name:
  template:
    src: templates/zabbix_agentd.conf.j2
    dest: /etc/zabbix/

