---

- hosts: status_up
  become: True
  become_method: sudo
  gather_facts: True
  vars_files:
    - base_config/vars/main.yml
    - snmp_hosts/vars/main.yml
    - zabbix_clients/vars/main.yml
  roles:
    - base_config
    - snmp_hosts
    - zabbix_clients
    

