---

- name: Ensure chronyd is restarted and enabled on boot
  systemd:
    name: chronyd
    state: restarted
    enabled: yes

- name: Restart Zabbix-Agent
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes
