---
- name: Add DNS server
  lineinfile:
      path: /etc/resolv.conf
      line: nameserver 172.24.39.253
      insertafter: '^search'
      state: present

- name: Add Ansible user
  user:
      name: ansible
      group: wheel
      update_password: always
      password: "{{ user_password }}"
      system: yes
      comment: "Ansible Management User"

- name: Ensure Custom fact directory exists
  file:
      path: /etc/ansible/facts.d/
      state: directory

- name: Add custom fact file
  copy:
      src: files/foreman_status.fact
      dest: /etc/ansible/facts.d/foreman_status.fact
      mode: 0755

- name: Check SSH key is in authorized_keys
  authorized_key:
      user: ansible
      state: present
      key: "{{ ssh_key }}"

- name: Install Foreman RPM
  yum:
      name: http://{{ foreman_host }}/pub/katello-ca-consumer-latest.noarch.rpm
      state: present
  tags:
        - satellite
  

- name: Register with Foreman
  redhat_subscription:
      state: present
      org_id: "{{ foreman_org }}"
      activationkey: "{{ foreman_act_key }}"
      pool_ids:
              - 2c98a78a63ed325b0163ed6141b60006
              - 2c98a78a63ed325b0163ed736acd00fc
  when:
        -  ansible_local.foreman_status != 'Current'   

  tags:
        - satellite

- name: Install Packages
  yum:
      name: "{{ item }}"
      state: present
  with_items:
      - vim
      - bash-completion
      - bind-utils

- name: Install Zabbix-agent
  yum:
      name: zabbix-agent
      state: present
      disable_gpg_check: yes
  notify: Start Zabbix-agent
  tags:
        - satellite
  
- name: Install oVirt Guest Agent
  yum: name=ovirt-guest-agent state=present
  notify: Start ovirt-guest-agent
  tags:
        - ovirt
                      
